### ISSUE TITLE
Oddity in value returned by `lookup` on master branch

### ISSUE THREAD

**Issue by ctb** [dib-lab/pybbhash#2]
the `lookup` function returns a bad value on the master branch, but not in the spacegraphcats branch. Not sure what's going on. @luizirber I'll pass you the test info when I get a chance to write it up.

```
(18446744073709551615, <class 'int'>, <class 'numpy.ndarray'>)
```

**Comment by luizirber** [comment]
the BooPHF lookup returns [`ULLONG_MAX`][0] if the element is not found.
The [previous version][1] of the Cython wrapper declared the lookup method as
```
int lookup(int)
```
when the correct signature is
```
uint64_t lookup(uint64_t)
```

Turns out that `18446744073709551615 == 2 ** 64 - 1 == ULLONG_MAX`,
so the previous version ended up returning `-1` because it was converting an unsigned value to a signed value (using two-complement).

On the spacegraphcats code it was working before because `-1` could be indexed in the [`mphf_to_kmer` numpy array][2], but `18446744073709551615` can't.

All of this can be fixed in a couple of ways:
- Keep it compatible with the current spacegraphcats implementation and return -1 if the lookup fails:
```
def lookup(self, uint64_t kmer):                                            
    cdef uint64_t value = deref(self.c_mphf).lookup(kmer)                   
    if value != ULLONG_MAX:                                                 
        return value                                                        
    return -1 
```
- Keep it compatible with `BooPHF` and return `ULLONG_MAX` (what is happening now)
- Return `None` if it is not found.

Personally I prefer the last option, returning `None`, but the first solution fixes the problem in spacegraphcats.

(and, please, an **oddity** in a SPACEgraphcats project should be a [space oddity][3], which makes me Ground Control and I guess you're Major Tom?)

[0]: https://github.com/dib-lab/pybbhash/blob/90085d59984b804cff9b40448ae8ee33775e3806/BooPHF.h#L987
[1]: https://github.com/dib-lab/pybbhash/blob/a14a72a546ec1c21dca031ad778e50a1cbb4112c/bbhash.pyx#L44
[2]: https://github.com/spacegraphcats/spacegraphcats/blob/777b033b869344d0fdeac8472d1a1f1474674da3/search/search_utils.py#L441
[3]: https://www.youtube.com/watch?v=D67kmFzSh_o

**Comment by ctb** [comment]
I prefer 'None' too; thanks for the troubleshooting!
